# Generated by Django 3.0.4 on 2020-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('seats', models.IntegerField(default=0)),
            ],
        ),
    ]
