# Generated by Django 3.0.8 on 2020-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=10)),
                ('number_of_seats', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('B', 'Booked')], default='B', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Booking Details',
            },
        ),
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=10)),
                ('price', models.IntegerField(default=10)),
                ('duration', models.CharField(max_length=30)),
                ('total_seats', models.IntegerField(default=0)),
                ('rem_seats', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Bus Information',
            },
        ),
    ]
