# Generated by Django 3.0.4 on 2020-07-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='startTime',
            field=models.CharField(max_length=10),
        ),
    ]
