# Generated by Django 3.0.4 on 2020-07-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200705_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
