# Generated by Django 3.0.4 on 2020-07-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200705_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businfo',
            options={'verbose_name_plural': 'Bus Information'},
        ),
        migrations.AddField(
            model_name='businfo',
            name='todayDate',
            field=models.DateField(auto_now=True),
        ),
    ]
