# Generated by Django 3.0.4 on 2020-07-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200705_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='todayDate',
        ),
    ]
