# Generated by Django 3.0.8 on 2020-07-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_businfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='date',
        ),
    ]
