# Generated by Django 3.0.8 on 2020-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_businfo_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=10)),
                ('total_seats', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('B', 'Booked')], default='B', max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='businfo',
            old_name='seats',
            new_name='rem_seats',
        ),
        migrations.AddField(
            model_name='businfo',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
