# Generated by Django 3.0.8 on 2020-07-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_businfo_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingdetails',
            options={'verbose_name_plural': 'Booking Details'},
        ),
    ]
