# Generated by Django 3.0.8 on 2020-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200719_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='number_of_seats',
            field=models.IntegerField(default=1),
        ),
    ]
