# Generated by Django 3.0.8 on 2020-07-21 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200720_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='bus_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businfo',
            name='rem_seats',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
