# Generated by Django 3.0.8 on 2020-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200721_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businfo',
            name='rem_seats',
            field=models.IntegerField(default=0),
        ),
    ]
